# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: main

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - name: Unit tests
        run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - name: Check package version
        id: cpv
        uses: PostHog/check-package-version@v2
        with:
          path: '.'
      - name: Show version info
        run: |
          echo "Committed version: ${{ steps.cpv.outputs.committed-version }}"
          echo "Published version: ${{ steps.cpv.outputs.published-version }}"
          echo "Is new version: ${{ steps.cpv.outputs.is-new-version }}"
      - run: npm ci
      - name: Publish new version
        if: steps.cpv.outputs.is-new-version == 'true'
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - uses: akhilmhdh/contributors-readme-action@v2.3.10
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
